### ISSUE TITLE
remake CBM_dataPrep_SK

### ISSUE THREAD

**Issue by cboisvenue** [cboisvenue/spadesCBM#44]
The managed forests of SK are the default example for spadesCBM. This example uses the data in the Boisvenue et al 2016 and was functional prior to building standAlone_core.R global for Scott. It needs to be adapted to the new structure brought on by the switch from C++ functions to libcbm function calls, and it needs to be cleaned up.

```[tasklist]
### Tasks
Discuss with Ben storing this "base" spatial layers on the cloud somewhere so we can all know we are using the same layers/datasets.
```

```[tasklist]
### Tasks
- [ ] SPU coordination with CAT. We need to check that the SPU map created in here matches what Scott uses in libcbm. 
Currently in CBM_dataPrep_SK.r, SPUs for Canada are read from a shape file (spUnit_Locator.shp) that I think was created by Ian Eddy. We need to make this more generalized. The current PSPU data is here: \\vic-fas2\cat\NFCMARS_admin\Data\SpatialFramework\PSPUS.zip 
Scott put that same shapefile on a googleDrive here is a link to PSPUS.zip
https://drive.google.com/file/d/1Z_pMwhylqMkKZfOArATaAz9pUVNXtBAd/view?usp=sharing
```
```[tasklist]
### Tasks
- [ ] Fix masterRaster: the masterRaster is not quite 30m. Need to figure out where the original raster came from and fix it.
```

```[tasklist]
### Tasks
- [ ] clean-up and streamline .inputObjects and script. CB was the only person that really work on this and inserted ##TODO
```
